booking/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('bookings/', views.booking, name='bookings'),
    path('create_booking/', views.createBooking, name="create_booking"),
    path('update_booking/<str:pk>/', views.updateBooking, name="update_booking"),
    path('delete_booking/<str:pk>/', views.deleteBooking, name="delete_booking"),
]

events/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.EventList.as_view(), name='events'),
    path('events/', views.createEvent, name="create_event"),
    path('update_event/<str:pk>', views.updateEvent, name="update_event"),
    path('delete_event/<str:pk>', views.deleteEvent, name="delete_event"),
]

nags_with_notions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pizza_system.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path("events/", include("events.urls"), name="events-urls"),
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizza_system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.myview, name='home')
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
STATUS = ((0, "Draft"), (1, "Booked"))

class Booking(models.Model):
    name = models.ForeignKey(
        User, on_delete=models.CASCADE,
    )
    location = models.TextField()
    phone = PhoneNumberField()
    booking_date = models.DateTimeField()
    guest_number = models.IntegerField()
    message = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    
    def __str__(self):
        return f"Booking request from {self.name}"

events/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0, "Draft"), (1, "Published"))

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
    User, on_delete=models.CASCADE, related_name="events"   
    )
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    event_image = models.ImageField(null=True, blank=True, upload_to="images/")
    class Meta:
        ordering = ["-created_on"]
    def __str__(self):
        return f"{self.title}"
    
    
class Comment(models.Model):
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ["created_on"]
    

pizza_system/models.py
from django.db import models

# Create your models here.

booking/forms.py
from django import forms
from .models import Booking


# Create a booking form
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('name', 'location', 'phone', 'booking_date','guest_number', 'message','status')
        
        widgets = {
            'name': forms.Select(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter venue location'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Please enter contact number'}),
            'booking_date': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Please enter date of event'}),
            'guest_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Please enter estimated guest number'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Please enter  any additional info.'}),
            'status': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        

events/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'slug', 'author', 'content', 'event_image', 'status')
                
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter event title'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.NumberInput(attrs={'class': 'form-control'}),
        }

pizza_system/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name' : 'Name', 
            'email' : 'Email',
        }

booking/views.py
from django.shortcuts import render, redirect
from .forms import BookingForm
from .models import Booking

# Create your views here.

def booking(request):
    """
    Renders the booking page
    """
    booking_form = BookingForm()
    bookings_list = Booking.objects.all()

    return render(
        request,
        "bookings.html",
        {
            "booking_form": booking_form,
            "bookings_list": bookings_list,
        },
    )
    
def createBooking(request):
    
    form = BookingForm()
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
            
    
    context = {'form': form}
    return render(request, 'booking_form.html', context)

def updateBooking(request, pk):
    
    booking = Booking.objects.get(id=pk)
    form = BookingForm(instance=booking)
    
    if request.method == 'POST':
        form = BookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('/bookings/')
    
    context = {'form': form}
    return render(request, 'booking_form.html', context)

def deleteBooking(request, pk):
    booking = Booking.objects.get(id=pk)
    print('in deletebooking', booking, request)
    if request.method == "POST":
        print('POSTED')
        booking.delete()
        return redirect('/bookings/')
        
    context = {'booking': booking}
    return render(request, 'delete.html', context)
    
    
    
    
    
    

events/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.views import generic
from .models import Event
from .forms import EventForm

# Create your views here.
class EventList(generic.ListView):
    queryset = Event.objects.all()
    template_name = "events/index.html"
    paginate_by = 3

@permission_required("events.view_event")
def createEvent(request):
    
    form = EventForm()
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/events')
            
    context={'form': form}
    return render(request, 'events/event_form.html', context)

@permission_required("events.view_event")
def updateEvent(request, pk):
    event = Event.objects.get(id=pk)
    form = EventForm(instance=event)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            return redirect('/events')
    context = {'form': form}
    return render(request, 'events/event_form.html', context)
    
    
@permission_required("events.view_event")
def deleteEvent(request, pk):
    event = Event.objects.get(id=pk)
    if request.method == "POST":
        event.delete()
        return redirect('/events')
    context = {'event': event}
    return render(request, 'events/delete.html', context)
    
    
    

nags_with_notions/views.py
from django.shortcuts import render


def handling_404(request, exception):
    render(request,'404.html')
    
    

pizza_system/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
def myview(request):
    print('request:', request)
    return render(request, "index.html")

booking/templates/booking/booking.html
<h1>Booking:{{booking}}</h1>

booking/templates/booking/booking_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<a href="{% url 'view' %}">Go back</a>
<div class="container d-flex align-items-center flex-column">
    <br>

<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete booking for the {{booking.booking_date}} ?</p>


    <a class="btn btn-warning" href="{% url 'view' %}">Cancel</a>

    <input class="btn btn-primary" type="submit" value="Delete" name="confirm">
</form>
</div>
{% endblock %}

booking/templates/booking/booking_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<a href="{% url 'view' %}">Go back</a>
<form method="POST">
    {% csrf_token %}

    <div  class="content-section d-flex justify-content-center">
        <fieldset  class="shadow-lg p-3 col-md-9 mb-5 mt-5 bg-white rounded">
            <h2 class="text-center">Create New Booking</h2>
            <div id='bookingform'>
            {{ form| crispy}}
            </div> 

            <input value="submit" type="submit" class="btn btn-primary mt-2"></input>
        </fieldset>
    </div>
</form>

{% endblock %}

booking/templates/booking/bookings.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <hr>
<h1 id="bookings_header" class="">{{request.user}}'s Bookings</h1>

    {% for booking in bookings %}
    <ul class="border border-secondary rounded p-5">
        <li>Date: {{booking.booking_date}}</li>
        <li>Address: {{booking.location}}</li>
        <li>Guest Numbers: {{booking.guest_number}}</li>
        <li class="mb-5">Message: {{booking.message}}</li>
        <a class="btn-primary text-decoration-none"  href="{% url 'update_booking' booking.id %}">Edit</a>
        <a class="btn-warning text-decoration-none" href="{% url 'delete_booking' booking.id %}">Delete</a>
    </ul>
    {% empty %}
    <h3>No items in list</h3>
    {% endfor %}
</div>


{% endblock %}

booking/templates/booking/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<!-- render register or login form depending on page argument -->

{% if page == 'register' %}

<div class="content-section d-flex justify-content-center">
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <legend class="border-bottom mb-4">Register Today</legend>
            {{ form|crispy}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% else %}

<div class="content-section d-flex justify-content-center">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <h3>Account Login</h3>
            <p>Welcome Back!</p>
            {{ form|crispy}}
            <div class="form-group">
                <input class="btn btn-outline-info" value="login" type="submit"></input>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't Have An Account? <a class="ml-2" href="{% url 'register' %}">Register</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% endif %}

{% endblock content %}

booking/templates/booking/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<!-- render register or login form depending on page argument -->

{% if page == 'register' %}

<div class="content-section d-flex justify-content-center">
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <legend class="border-bottom mb-4">Register Today</legend>
            {{ form|crispy}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% else %}

<div class="content-section d-flex justify-content-center">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <h1>Register</h1>
            {{ form|crispy}}
            <div class="form-group">
                <input class="btn btn-outline-info" value="register" type="submit"></input>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Have An Account? <a class="ml-2" href="{% url 'login' %}">Login</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% endif %}

{% endblock content %}

booking/templates/booking_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Add Booking</h1>

<div class="form-group">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" name="submit">
    </form>
</div>




{% endblock %}

booking/templates/bookings.html
{% extends 'base.html' %}

<body>

    {% block content %}


    <form method="post" action="{% url 'bookings' %}">
        {% csrf_token %}
        <table>


            {% for booking in bookings_list %}


            {% if user == booking.name %}

            <strong>Date booked: {{booking.booking_date}}</strong>
            <a class="btn btn-sm btn-info" href="{% url 'update_booking' booking.id %}">Update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'delete_booking' booking.id %}">Delete</a>

            <ul>
                <li>{{booking.name}}</li>
                <li>Booking ID: #{{booking.id}}</li>
                <li>Address: {{booking.location}}</li>
                <li>Guest Numbers: {{booking.guest_number}}</li>
                <li>Message: {{booking.message}}</li>
                <li>Phone: {{booking.phone}}</li>
                <li>Status: {{booking.status}}</li>

            </ul>
            <br />
        </table>
    </form>
    {% endif %}

    {% endfor %}



    {% endblock content %}
</body>

booking/templates/bookings_list.html
{% extends 'base.html' %}

<body>

    {% block content %}

    <form method="post" action="{% url 'bookings-list' %}">
        {% csrf_token %}
        <table>
            <h1>Your Bookings</h1>

            {% for booking in bookings_list %}
            <li>{{booking}}</li>
            <strong>Date booked: {{booking.booking_date}}</strong>
            <button formnovalidate name='edit' value="{{booking.id}}" class="btn btn-secondary">Edit</button>
            <button formnovalidate name='delete' value="{{booking.id}}" class="btn btn-secondary">Delete</button>

            <ul>
                <li>Booking ID: #{{booking.id}}</li>
                <li>Address: {{booking.location}}</li>
                <li>Guest Numbers: {{booking.guest_number}}</li>
                <li>Message: {{booking.message}}</li>
                <li>Phone: {{booking.phone}}</li>
                <li>Status: {{booking.status}}</li>

            </ul>
            <br />
        </table>
    </form>

    {% endfor %}
    {% endblock content %}
</body>

booking/templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<p>{{booking.name}} are you sure you want to delete booking ref #{{booking.id}}</p>

<form action="{% url 'delete_booking' booking.id %}" method="POST">
    {% csrf_token %}

    <a href="{% url 'bookings' %}">Cancel</a>

    <input type="submit" name="confirm">
</form>
{% endblock %}

booking/templates/submit.html
<div class="row justify-content-center">
    <div class="col-12 col-md-6 my-5">
        <h2>Add Booking To Database</h2>


        {% if submitted %}
        Your booking was submitted Successfully!!
        {% else %}

        <form method="post">
            {{form.name}}
            {{form.phone}}
            {{ form.booking_date }}
            {{ form.guest_number }}
            {{ form.status }}
            {{ booking_form.as_p }}
            {% csrf_token %}
            <button name='submit' value="{{booking.id}}" class="btn btn-secondary">Submit</button>
        </form>
        {% endif %}
    </div>
</div>

booking/templates/view.html
{% extends "base.html" %}

{% block content %}
{{form}}
{% for booking in user.booking.all %}
<form method="POST">
    <div class="list-group container mt-5">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-6">
                <ul>
                    <li class="list-group-item">{{booking.booking_date}}</li>
                    <li class="list-group-item">{{booking.location}}</li>
                    <li class="list-group-item">{{booking.guest_number}}</li>
                    <li class="list-group-item">{{booking.message}}</li>
                    <a class="btn btn-primary" href="{% url 'update_booking' booking.id %}">Update</a>
                    <a class="btn btn-warning"href="{% url 'delete_booking' booking.id %}">Delete</a>
                </ul>
            </div>
        </div>
    </div>
</form>
{% endfor %}
{% endblock %}

events/templates/events/delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<p>Are you sure you want to delete event ref#{{event.id}}</p>

<form action="{% url 'delete_event' event.id %}" method="POST">
    {% csrf_token%}

    <a href="{% url 'events' %}">Cancel</a>

    <input type="submit" name="Confirm">
</form>


{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<a href="{% url 'view' %}">Go back</a>
<div class="container d-flex align-items-center flex-column">
    <br>

<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this event?</p>


    <a class="btn btn-warning" href="{% url 'events' %}">Cancel</a>

    <input class="btn btn-primary" type="submit" value="Delete" name="confirm">
</form>
</div>
{% endblock %}

events/templates/events/event_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="form-group" enctype="multipart/form-data">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Add Event</h1>
        {{ form.as_p }}

        <input type="submit" name="submit">
    </form>
</div>


{% endblock %}

events/templates/events/index.html
{% extends "base.html" %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Event Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for event in event_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="author">Author: {{ event.author }}</p>
                                </div>
                            </div>
                            <a href="#" class="event-link">
                                <h2 class="card-title">{{ event.title }}</h2>
                            </a>
                            <a href="#" class="event-link">
                                {% if event.event_image %}
                                <h2 class="card-title"><img src="{{ event.event_image.url }}" width="300" height="300">
                                </h2>
                                {% endif %}
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ event.created_on}}
                            </p>
                            {% if perms.event.can_add_new_event %}
                            <a class="btn btn-sm btn-info" href="{% url 'update_event' event.id %}">Update</a>
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_event' event.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> PREV &laquo;</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

pizza_system/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">

    <title>Bootstrap 5  Login Page Design</title>
  </head>
  <body>
    <section class="form-01-main">
      <div class="form-cover">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="form-sub-main">
              <div class="_main_head_as">
                <a href="#">
                  <img src="assets/images/vector.png">
                </a>
              </div>
              <div class="form-group">
                  <input id="email" name="email" class="form-control _ge_de_ol" type="text" placeholder="Enter Email" required="" aria-required="true">
              </div>

              <div class="form-group">                                              
                <input id="password" type="password" class="form-control" name="password" placeholder="********" required="required">
                <i toggle="#password" class="fa fa-fw fa-eye toggle-password field-icon"></i>
              </div>

              <div class="form-group">
                <div class="check_box_main">
                  <a href="#" class="pas-text">Forgot Password</a>
                </div>
              </div>

              <div class="form-group">
                <div class="btn_uy">
                  <a href="#"><span>Login</span></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section>
  </body>
</html>

pizza_system/templates/pizza_system/login_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<!-- render register or login form depending on page argument -->

{% if page == 'register' %}

<div class="content-section d-flex justify-content-center">
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <legend class="border-bottom mb-4">Register Today</legend>
            {{ form|crispy}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% else %}

<div class="content-section d-flex justify-content-center">
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <fieldset class="form-group shadow-lg p-3 mb-5 mt-5 bg-white rounded">
            <h3>Account Login</h3>
            <p>Welcome Back!</p>
            <div class="mb-3">
                <input type="text" name="username" class="form-control w-auto" placeholder="Username">
            </div>
            <div class="mb-3">
                <input type="password" name="password" class="form-control w-auto" placeholder="Password">
            </div>
            {{ form|crispy}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't Have An Account? <a class="ml-2" href="{% url 'register' %}">Register</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>



{% endif %}

{% endblock content %}

templates/about.html
<div class="outerdiv">
    <div class="container">
        <h1 class="text-center">About Us</h1>
        <div class="row text-center">
            <div class="col-md-6">
                <img id="aboutImg" height="100" width="100" src="/static/images/about2.jpg" alt="contact info with several imgs">
            </div>
            <div class="col-md-6">
                <p> Nags with Notions provides delicious, fresh pizzas for any event. It is run by Caroline and Tamara, who would love
                    to add to the uniqueness of your special occasion.
                    <br><br>
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'view' %}" id="bknowlink" aria-label="brings user to booking page">
                        Book our service so you can have delicious pizzas at your event
                    </a>
                    <div id="myAlert2" class="alert alert-warning collapse">
                        <strong>You must login to book!</strong>
                        <a id="linkClose2" href="#" class="close" >&times;</a>
                    </div>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'create_booking' %}" class="btn btn-primary">Book our service so you can have delicious pizzas at your event</a>
                    {% endif %}</p>
            </div>
        </div>
    </div>
</div>

templates/footer.html
<footer>

    <div class="footer-top">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 mx-auto">
                    <div class="col-lg-4">
                        <img class="col-lg-4__logo__img mb-3" src="/static/admin/img/nags-with-notions-logo.webp"
                        srcset="/static/admin/img/nags-with-notions-logo100x95px.webp 200w" sizes='100vw'
                            alt="pink horse with Nags logo">
                        <p>Sourdough Pizzas from Meaths finest food producers</p>
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    <h6 class="mt-4">CONTACT</h6>
                    <p class="mb-1">0863371314</p>
                    <p class="mb-1">caroline@nagswithnotions.ie</p>
                    <p class="mb-1">0867506453</p>
                    <p class="mb-0">tamara@nagswithnotions.ie </p>
                </div>
                <div class="col-lg-4 mx-auto">
                    <p><a class="text-dark" aria-label="facebook" href="https://m.facebook.com/p/Nags-with-Notions-Pizza-100094122740703/"><i class="fa-brands fa-facebook-f"></i> Facebook</p></a>
                    <p><a class="text-dark" aria-label="instagram" href="https://www.instagram.com/nagswithnotions/"><i class="fa-brands fa-instagram"></i> Instagram</p></a>
                    <p><a class="text-dark" aria-label="github" href="https://github.com/JWalshe86/"><i class="fa-brands fa-github"></i> Github</p></a>
                    <p><a class="text-dark" aria-label="linkedin" href="https://www.linkedin.com/in/john-walshe86/"><i class="fa-brands fa-linkedin"></i> Linkedin</p></a>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <p class="mb-0">Copyrights all rights reserved</p>
                </div>
                <div class="col-auto">
                    <p class="mb-0">Designed by <a href="https://github.com/JWalshe86/">John</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}